### ISSUE TITLE
k8s-dashboard exec is giving black screen intermittently & sometime with error - Sending Error: Error: http status 404

### ISSUE THREAD

**Issue by shnigam2** [OpenUnison/openunison-k8s#105]
Issue - When trying exec into pod through kubernetes dashboard , intermittently giving black screen with error `Sending Error: Error: http status 404`
<img width="1389" alt="image" src="https://github.com/OpenUnison/openunison-k8s/assets/75428408/377dc7aa-c6fe-48b8-8ea9-852fc65eeff7">

EKS version - 1.26.7
k8s-dashboard version - 6.0.8
Openunison version -    
```     
chart: orchestra-login-portal-argocd
        targetRevision: 2.3.50
```
Values for dashboard
```
            dashboard:
              namespace: "kubernetes-dashboard"
              cert_name: "kubernetes-dashboard-certs"
              label: "k8s-app=kubernetes-dashboard"
              service_name: kubernetes-dashboard
              require_session: true
```

**Comment by shnigam2** [comment]
@mlbiam Request to please check

**Comment by mlbiam** [comment]
what versions of the containers are you running?

**Comment by shnigam2** [comment]
@mlbiam please find log from openunison pod for version
```
k logs openunison-openunison-d4696498b-4cpns -n openunison |head
/usr/local/openunison/work/webapp/WEB-INF/lib/*:/usr/local/openunison/work/webapp/WEB-INF/classes:/tmp/quartz
[2024-03-16 00:05:25,763][main] INFO  OpenUnisonOnUndertow - Starting OpenUnison on Undertow 1.0.37-2023072501
```

**Comment by shnigam2** [comment]
@mlbiam Could you please take a look, we are using  below version and corresponding images. We are facing issues with dashboard exec intermittently with 2 replicas of dashboard, But we have tried keeping 1 replica of dashboard it worked fine then. How could we fix dashboard exec issue by keeping 2 replicas of dashboard.
```
chart: orchestra-login-portal-argocd
        targetRevision: 2.3.50
```

```
            impersonation:
              use_jetstack: true
              explicit_certificate_trust: true
              ca_secret_name: letsencrypt-ca
```
Dashboard ingress values:-
```
              openunison-dashboard:
                annotations:
                  kubernetes.io/ingress.class: nginx
                  certmanager.k8s.io/cluster-issuer: letsencrypt
                  nginx.ingress.kubernetes.io/server-alias: {{ metadata.annotations.environment }}-dashboard-{{ metadata.annotations.name }}.company.com
                  nginx.ingress.kubernetes.io/upstream-vhost: {{ metadata.annotations.environment }}-dashboard-{{ metadata.annotations.name }}.company.com
                  nginx.ingress.kubernetes.io/affinity: cookie
                  nginx.ingress.kubernetes.io/backend-protocol: https
                  nginx.ingress.kubernetes.io/secure-backends: 'true'
                  nginx.ingress.kubernetes.io/session-cookie-hash: sha1
                  nginx.ingress.kubernetes.io/session-cookie-name: openunison-orchestra
                  nginx.org/ssl-services: openunison-orchestra
                hosts:
                - name: dashboard.{{ metadata.annotations.fqdn }}
                  service:
                  - externalPort: 443
                    servicename: openunison-orchestra
                    path: "/"
                    pathType: ImplementationSpecific
                  tls: true
                namespace: openunison
```
