### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by MichaelTrip** [OpenUnison/openunison-k8s#106]
As i was exploring the Openunison solution i tried to deploy it onto my arm64 Oracle VPS. But that didn't work due to the lack of arm64 support. I already reated a PR for the operator... but changing the maven on how to compile things is out of my league. Is it possible to create a arm64 image?

**Comment by mlbiam** [comment]
It's working in beta now. Follow the directions at https://openunison.github.io/deployauth/ but make sure you set the following in your values.yaml:

```yaml
image: docker.io/mlbiam/openunison-k8s:1.0.42
impersonation:
  jetstack_oidc_proxy_image: ghcr.io/mlbiam/kube-oidc-proxy:1.0.7-17711b
openunison:
  precheck:
    image: ghcr.io/mlbiam/python-slim-nonroot/python3:1.0.0-c36113
  html:
    image: ghcr.io/mlbiam/openunison-k8s-react:1.0.1-cc9ade
operator:
  image: ghcr.io/mlbiam/openunison-kubernetes-operator:1.0.6-592ebd
```

This will get rolled into our next release after Thanksgiving
