### ISSUE TITLE
Groups not showing from Google Workspace

### ISSUE THREAD

**Issue by davisonja** [OpenUnison/openunison-k8s#110]
I've been following https://www.tremolosecurity.com/post/kubernetes-and-google-workspace, which has worked well for using Google Workspace as the source of our user info.

However, the portal is showing nothing for the "Roles" section of the user profile, and the group names are (not unexpectedly, given nothing is showing on the profile) not working for RBAC dashboard access.

Is there somewhere I can find some logs on the group fetching authentication chain?

**Comment by mlbiam** [comment]
Can you provide your values.yaml?  The logs for the `openunison-orchestra` pod may have some information.  Most likely cause is that the workflows weren't deployed or integrated.  What does `kubectl get authchain google-ws-load-groups -n openunison` return?

**Comment by davisonja** [comment]
```
❯ kubectl get authchain google-ws-load-groups -n openunison
NAME                    AGE
google-ws-load-groups   46h
```

There wasn't anything directly obvious as relating to groups in the orchestra pod logs, tho I'm not sure what this relates to:
```
[2024-05-22 01:08:10,267][Thread-21] WARN  OpenShiftTarget - Unexpected result calling 'https://kubernetes.default.svc/apis/openunison.tremolo.io/v2/namespaces/openunison/oidc-sessions/xabcdefgh-abcd-abcd-abcd-abcdefghijklx' - 404 / {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"oidc-sessions.openunison.tremolo.io \"xabcdefgh-abcd-abcd-abcd-abcdefghijklx\" not found","reason":"NotFound","details":{"name":"xabcdefgh-abcd-abcd-abcd-abcdefghijklx","group":"openunison.tremolo.io","kind":"oidc-sessions"},"code":404}
```
They appear in groups of three, each with their own value between the `x`s (which I've alphabetised above)



values.yaml, with commented out things removed, and ids cropped; most of it is the same as the defaults:
```
network:
  openunison_host: "k8sou-staging.fred.com"
  dashboard_host: "k8sdb-staging.fred.com"
  api_server_host: "k8sapi-staging.fred.com"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://k8s-api-staging.internal.fred.com:6443
  force_redirect_to_tls: false
  createIngressCertificate: false
  ingress_type: nginx
  ingress_annotations: {cert-manager.io/issuer: "letsencrypt-staging"}

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: openunison-cp
enable_impersonation: true

impersonation:
  use_jetstack: true
  explicit_certificate_trust: true

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
  require_session: true

certs:
  use_k8s_cm: false

trusted_certs: []

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

oidc:
  client_id: id-body.apps.googleusercontent.com
  issuer: https://accounts.google.com
  user_in_idtoken: false
  domain: ""
  scopes: openid email profile
  claims:
    sub: email
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups

network_policies:
  enabled: false
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: true
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []

openunison:
  replicas: 1
  non_secret_data:
    K8S_DB_SSO: oidc
    PROMETHEUS_SERVICE_ACCOUNT: system:serviceaccount:monitoring:prometheus-k8s
    SHOW_PORTAL_ORGS: "false"
  secrets: []
  enable_provisioning: false
  use_standard_jit_workflow: true
  #az_groups:
  #- CN=k8s-users,CN=Users,DC=ent2k12,DC=domain,DC=com

google_ws:
  admin_email: "julian@fred.com"
  service_account_email: "service.account@app.iam.gserviceaccount.com"

openunison.include_auth_chain: google-ws-load-groups
```

**Comment by mlbiam** [comment]
I think I see the issue.  `openunison.include_auth_chain: google-ws-load-groups` needs to be adding `include_auth_chain: google-ws-load-groups` to the `openunison` section of your values.yaml.

**Comment by davisonja** [comment]
That'll teach me for too blindly copy and pasting, rather than thinking about what the aim was!

That certainly changed the behaviour, tho now I'm getting
```
[2024-05-22 02:30:10,220][XNIO-1 task-1] ERROR ConfigSys - Could not process request
org.graalvm.polyglot.PolyglotException: null
```
errors when I attempt to login to the portal (I can choose my Google Workspace account, but then get an error page, and the orchestra pod shows several of those errors)

**Comment by mlbiam** [comment]
Did you create the `googlews` `Secret` in the `openunison` `namespace` with the key `key` with your Google SA?

**Comment by davisonja** [comment]
Oh dear, in chasing down problems with the Google SA that value got loaded with the key `data` not `key`. 
Switching that so the value was called `key` instead sorted it all, thank you very much! It works beautifully now.

I did initially (once thek ey was sorted) get a 403 from Google (in the orchestra pod):
```
Admin SDK API has not been used in project <id-number> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/admin.googleapis.com/overview?project=<id-number> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
Enabling the API has it all working and groups coming through nicely.
But... Is that a sign I've messed something else up?

**Comment by davisonja** [comment]
This is all working nicely, since I fixed up the Secret, thanks for all the help!

**Comment by vilnitsky** [comment]
Good day @mlbiam ! would you be able to help me with a similar issue please

I have followed these steps https://www.tremolo.io/post/kubernetes-and-google-workspace to configured Google OIDC

I think I am facing some issue with the Secret key
on login once I am athenticated at google and redirected back in logs I have this error

> [2024-11-05 23:38:50,386][XNIO-1 task-1] ERROR ConfigSys - Could not process request                                                                                                  │
> │ org.graalvm.polyglot.PolyglotException: unable to convert key pair: Cannot invoke "org.bouncycastle.asn1.pkcs.PrivateKeyInfo.getPrivateKeyAlgorithm()" because "<parameter1>" is null │     at org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter.getPrivateKey(Unknown Source) ~[bcpkix-jdk18on-1.78.1.jar:?]                                                                │     at <js>.doAuth(Unnamed:68) ~[?:?]                                                                                                                                                 │     at org.graalvm.polyglot.Value.execute(Value.java:881) ~[graal-sdk-23.0.5.jar:?]                                                                                                   │     at com.tremolosecurity.proxy.auth.JavaScriptAuth.doGet(JavaScriptAuth.java:66) ~[unison-server-core-1.0.41.jar:?]                                                                 │     at com.tremolosecurity.proxy.auth.sys.AuthManagerImpl.execAuth(AuthManagerImpl.java:452) ~[unison-server-core-1.0.41.jar:?]  
> 
> 

The secret was deployed with this config:


> apiVersion: v1
> kind: Secret
> metadata:
>   name: googlews
>   namespace: openunison
> type: Opaque
> data:
>   key: LS0tLS1CRUdJTiBQ


in my values I have got the necessary data:

```
oidc:
  client_id: google-id.apps.googleusercontent.com
  issuer: https://accounts.google.com
  user_in_idtoken: false
  domain: ""
  scopes: openid email profile
  claims:
    sub: name
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups


openunison:
  include_auth_chain: google-ws-load-groups

google_ws:
  admin_email: "email@myemail.com"
  service_account_email: "support@app.iam.gserviceaccount.com"
```

**Comment by vilnitsky** [comment]
wanted to leave a note for this article  https://www.tremolo.io/post/kubernetes-and-google-workspace


```
Give your service account a name, id, and description. Don't worry about granting any service access or user access. Once the service account is created, click on it and get the Unique ID on the next screen. Also, click on KEYS and then ADD KEY. Choose a JSON file and then download it. The JSON file will contain a PEM encoded private key. Create a Secret in the openunison namespace called googlews with a single key called key that contains the private key (and ONLY the private key, do not include the rest of the json). It should look like:

apiVersion: v1
kind: Secret
metadata:
  name: googlews
  namespace: openunison
type: Opaque
data:
  key: LS0tLS1CRUdJ..
```

  
 not sure if it's obvious for everyone, I had an issue because json file also contains new lines in pem like this:
` z/RSQ/b+\n-----END PRIVATE KEY-----\n",`
  
 it leads to a broken encoded certificate in base64 
 
 I had to replace all new lines '\n'  with actual new lines first to make it working
