### ISSUE TITLE
keycloak integration issue

### ISSUE THREAD

**Issue by yoonjaeyol** [OpenUnison/openunison-k8s#126]
We are integrating openunison with keycloak. 

it is my config

```yaml
network:
  openunison_host: "k8sou.apps.10-10-20-50.nip.io"
  dashboard_host: "k8sdb.apps.10-10-20-50.nip.io"
  api_server_host: "k8sapi.apps.10-10-20-50.nip.io"                                                                                                                                                                  session_inactivity_timeout_seconds: 900                                                                                                                                                                            k8s_url: https://0.0.0.0:6443                                                                                                                                                                                      force_redirect_to_tls: false                                                                                                                                                                                       createIngressCertificate: true                                                                                                                                                                                     ingress_type: nginx                                                                                                                                                                                                ingress_annotations:                                                                                                                                                                                                 kubernetes.io/ingress.class: nginx
cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"

image: "ghcr.io/openunison/openunison-k8s:1.0.41"
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: false
myvd_configmap: ""

#dashboard:
#  namespace: "kubernetes-dashboard"
#  cert_name: "kubernetes-dashboard-certs"
#  label: "k8s-app=kubernetes-dashboard"
#  service_name: kubernetes-dashboard
#certs:
#  use_k8s_cm: false


dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  new_label: "app.kubernetes.io/part-of=kubernetes-dashboard"
  service_name: kubernetes-dashboard
  auth_service_name: kubernetes-dashboard-auth
  api_service_name: kubernetes-dashboard-api
  web_service_name: kubernetes-dashboard-web
  enabled: true
certs:
  use_k8s_cm: false

trusted_certs:
  - name: ldaps
    pem_b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlekNDQW1PZ0F3SUJBZ0lFR2owUUZ6QU5CZ2txaGtpRzl3MEJBUXNGQURCdE1Rd3dDZ1lEVlFRR0V3TmsKWlhZeEREQUtCZ05WQkFnVEEyUmxkakVNTUFvR0ExVUVCeE1EWkdWMk1Rd3dDZ1lEVlFRS0V3Tm
taWFl4RERBSwpCZ05WQkFzVEEyUmxkakVsTUNNR0ExVUVBeE1jWVhCaFkyaGxaSE11WVdOMGFYWmxaR2x5WldOMGIzSjVMbk4yCll6QWdGdzB5TVRBM01EVXdNRFV6TWpoYUdBOHlNVEl4TURZeE1UQXdOVE15T0Zvd2JURU1NQW9HQTFVRUJoTUQKWkdWMk1Rd3dDZ1lEVlFRSUV3T
mtaWFl4RERBS0JnTlZCQWNUQTJSbGRqRU1NQW9HQTFVRUNoTURaR1YyTVF3dwpDZ1lEVlFRTEV3TmtaWFl4SlRBakJnTlZCQU1USEdGd1lXTm9aV1J6TG1GamRHbDJaV1JwY21WamRHOXllUzV6CmRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFD
NlNVQUJRSUZkYnRwZGJ3WEEKT05ablJVQlFBMEVyK2hWYmkxUHNWSnNaaUlGZjhJRC8xZXBPN0M4QlViVXN1U3dWWkc5ZEJIV3o0RFBwWUUrKwp2dmxrTEs1cEdiTnJQbDdFd241clJLRE5PeVR5ZUNBcFMzSVNsRW1iaVNQUjBuYXd5ckpoNjhQQ0I1bURSNTNmCmh1bFhPQ0dTd3Z
NN2RwM2RPc3lFQmRlVkw3aTFnbkJNYi9wN05YdTN5WmlWaDlpS3pqaENrZndqL0VsNTZaUHEKYmsvOGtQN0xBdTFvZGJWTkZGSUx5clB6SFBFU3I3N0preHcvKytPTmhtblA2UFBiU3FtRm0rcUVEYWhQanBFZgpscUdaY3BsOEZ0VXBzTG5JK3B4blI5eWU5ZUNpVDVuaDhlTEhobk
VFNzFpVE1rb2xrSHdxSm5xV1R3ZlF2b1g5CkM2SERBZ01CQUFHaklUQWZNQjBHQTFVZERnUVdCQlRjOGlDU055NnhSM2M5OU1aYkZUODgzREs1V0RBTkJna3EKaGtpRzl3MEJBUXNGQUFPQ0FRRUFOMEkwZnJDSzdYNGRHRmpGLzFpb3czUUwvbTcwemVIemlQVVFFUUdONXBFMwpyM
lZZL0ZHWGdNV0tFSXpHa2hMZW5CUXRxRE5Pbm4vL1JjK0Y2anM1RkNOVXhaT2V4ekl2aElhY0M4YUhzRWpFClRnclI5OWNqUVdsdzFhSVF0YUhkSmVqYXdYcU50YU1FMSt4RlJBQTNCWUF1T3BveW9wQ0NoMXdJaTEvQk84TlQKVmFaancxQU8xd1ZUaTJ3SUtCSUp1Z0N2T0dYZEt3
YzBuL0I4bzRRQkpScklRZEJnbzJVNjFBbkMxaWM4b0d3RwpxekN1V0dDenZjam9xNWFNcTliS0YyNHBQaDR3cWZMZnZGdWNsYmFIUlBiSmpxT3l0V3gzczhNV0lvRUNzdlhLCnhIYmJvSnU0c1AwLzRBMGQ4K25OOXI1MU8xalFaWHd0b3hwenFTV2ZlZz09Ci0tLS0tRU5EIENFUlR
JRklDQVRFLS0tLS0=

oidc:
  client_id: onepredict
  issuer: http://keycloak.10-10-20-50.nip.io/realms/onepredict
#  auth_url: http://keycloak.10-10-20-50.nip.io/realms/onepredict/protocol/openid-connect/auth
#  token_url: http://keycloak.10-10-20-50.nip.io/realms/onepredict/protocol/openid-connect/token
  user_in_idtoken: false
#  userinfo_url:  http://keycloak.10-10-20-50.nip.io/realms/onepredict/protocol/openid-connect/userinfo
  domain: ""
  scopes: openid email profile
  claims:
    sub: sub
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups

operator:
    legacy: false


monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

impersonation:
  use_jetstack: false
  jetstack_oidc_proxy_image: docker.io/tremolosecurity/kube-oidc-proxy:latest
  explicit_certificate_trust: true
  ca_secret_name: ou-tls-certificate

network_policies:
  enabled: false
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: false
    labels:
      app.kubernetes.io/name: kube-system


services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
    #openunison:
    #  replicas: 1
    #  non_secret_data: {}
    #    K8S_DB_SSO: oidc
    #  secrets: []

openunison:
  replicas: 1
  non_secret_data:
    K8S_DB_SSO: oidc
  secrets: []
  html:
    image: docker.io/tremolosecurity/openunison-k8s-html
  enable_provisioning: false
  use_standard_jit_workflow: true
```

I also currently have keycloak set up so that I can create a user but not log in.
So I checked the logs and found the following log.

[2024-10-14 05:10:29,661][XNIO-1 task-3] INFO  AccessLog - SRCH op=5 con=4 base='o=Tremolo' filter='(uid=dc9e6072-611f-4a54-bab5-b70ca92150ff)' scope='2' attribs=''
[2024-10-14 05:10:29,662][XNIO-1 task-3] INFO  AccessLog - RESULT op=5 con=4 result=0 time=1
[2024-10-14 05:10:29,662][XNIO-1 task-3] INFO  AccessLog - SRCH-RESULT op=5 con=4 entries=0 time=1                                                                                                                 [2024-10-14 05:10:29,663][XNIO-1 task-3] ERROR JITAuthMech - Could not execute workflow 'jitdb' on 'sub=dc9e6072-611f-4a54-bab5-b70ca92150ff,ou=oidc,o=Tremolo'com.tremolosecurity.provisioning.core.ProvisioningEx
ception: Could not reload user

In a browser, it looks like this

<img width="967" alt="image" src="https://github.com/user-attachments/assets/b4caf9a0-64d6-4638-999e-a7cf39159d0a">

What should I look for so I can fix this?
