### ISSUE TITLE
ERROR ConfigSys - Could not process request

### ISSUE THREAD

**Issue by burakkaracay** [OpenUnison/openunison-k8s#24]
Hello all,

I am trying to entegrate our k8s cluster with AD. We have istio in our k8s.
I applied the below steps: ( by following https://openunison.github.io/deployauth/ ) 
```
kubectl create ns openunison
kubectl label namespace openunison istio-injection=enabled
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml
helm repo add tremolo https://nexus.tremolo.io/repository/helm/
helm repo update
helm install openunison tremolo/openunison-operator --namespace openunison
kubectl apply -f orchestra-secrets-source.yaml
helm install orchestra tremolo/orchestra --namespace openunison -f openunison-default.yaml
```

After these steps, when I check the openunison-operator pod logs, I see these messages:
```
https://10.248.0.1:443/apis/openunison.tremolo.io/v6/namespaces/openunison/openunisons?watch=true&timeoutSeconds=30&resourceVersion=122257757
https://10.248.0.1:443/apis/openunison.tremolo.io/v6/namespaces/openunison/openunisons?watch=true&timeoutSeconds=30&resourceVersion=122257757
```

And openunison-orchestra pod logs has these error messages:
```
[2022-03-04 12:41:32,575][XNIO-1 task-1] INFO  AccessLog - [AzSuccess] - CheckAlive - https://127.0.0.1:8443/check_alive - uid=Anonymous,o=Tremolo -  [127.0.0.1] - [f07bdeaea6428cdf2fd221c440c503f4a651b9e32]
[2022-03-04 12:41:42,536][XNIO-1 task-1] INFO  AccessLog - [Error] - UNKNOWN - https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration - cn=none - NONE [127.0.0.1] - [fa5c50d59b4b22bdf165343329f51ee51750a43bc]
[2022-03-04 12:41:42,536][XNIO-1 task-1] ERROR ConfigSys - Could not process request
javax.servlet.ServletException: Unknown URI : /auth/idp/k8sIdp/.well-known/openid-configuration
```
Here is openunison-default.yaml configuration:
```
network:
  openunison_host: "login.k8s.brk.com.tr"
  dashboard_host: "dashboard.k8s.brk.com.tr"
  api_server_host: ""
  session_inactivity_timeout_seconds: 900
  k8s_url: https://xx.yy.zz.tt:6443
  createIngressCertificate: false
  ingress_type: istio
  ingress_certificate: my-wildcard-credential

k8s_cluster_name: cluster.local
enable_impersonation: false
dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard

certs:
  use_k8s_cm: false
trusted_certs: []
monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:kube-prometheus-stack-prometheus

active_directory:
  base: cn=users,dc=brk,dc=com,dc=tr
  host: "ldapserver.brk.com.tr"
  port: "636"
  bind_dn: "cn=brkk8s,cn=users,dc=brk,dc=com,dc=tr"
  con_type: ldaps
  srv_dns: "false"
```
And  I have my-wildcard-credential secret at istio-system namespace. And my AD has trusted certificate.

What might be the reason of "ConfigSys - Could not process request" errors?

Thanks for your help.

Regards
