### ISSUE TITLE
Help with using ALB Ingress Controller

### ISSUE THREAD

**Issue by alenhodzic85** [OpenUnison/openunison-k8s#30]
Hello,
I am using ALB Ingress Controller (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/), is it supported?

Kind Regards
Alen

**Comment by alenhodzic85** [comment]
Hi,
1. If you mean by downstream TLS traffic from ALB to service, there is an anotation (https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/ingress/annotations/#backend-protocol)
    alb.ingress.kubernetes.io/backend-protocol: HTTPS

2. Here is the sample:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: ${var.someCertArn}
    alb.ingress.kubernetes.io/healthcheck-path: /dashboard/
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
    meta.helm.sh/release-name: kubernetes-dashboard
    meta.helm.sh/release-namespace: kube-dashboard
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
  labels:
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-dashboard
    app.kubernetes.io/version: 2.5.1
    helm.sh/chart: kubernetes-dashboard-5.3.1
  name: kubernetes-dashboard
  namespace: kube-dashboard
spec:
  rules:
  - host: dashboard.example.com
    http:
      paths:
      - backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
        path: /*
        pathType: ImplementationSpecific
```

3. No, ALB is Application L7 LB. Certificate is hosted in AWS ACM. You can se the example annotation above: `alb.ingress.kubernetes.io/certificate-arn`

**Comment by mlbiam** [comment]
This is great!  There's one issue I can see though:

> No, ALB is Application L7 LB.

The ALB doesn't support SPDY, so kubectl exec/cp/port-forward won't work.  From inside the dashboard you'll be able to use the terminal function.  With other L7 load balancers, you can usually do pass-through for TLS (this is how we support istio & envoy which also do not support SPDY).

That said, this looks like it should be pretty straight forward.  Let me take a crack at it and you should see something from me in the next day or two

**Comment by alenhodzic85** [comment]
Ok great. While I wait, can you please provide me with a sample oidc configuration for the Azure IdP - if you have any? I want to try it with nginx ingress while I wait.

**Comment by mlbiam** [comment]
as luck would have it i'm writing that up now! (including mapping from group id --> name for easier RBAC integration)

**Comment by mlbiam** [comment]
instructions for AzureAD - https://openunison.github.io/identity%20providers/azuread/

**Comment by mlbiam** [comment]
I've got this working.  First, update your helm repos.  Next, in your values.yaml:

| Helm Chart Setting | Values |
| ------------------- | ------- |
|  `network.ingress_type` | `simple` |
| `network.service_type` | `NodePort` |
| `network.createIngressCertificate` | `false` |
| `network.ingress_annotations` | See Below |
| `impersonation.explicit_certificate_trust` | false |

For `network.ingress_annotations`, use:

```yaml
network:
  ingress_annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: "my-cert-arn"
    alb.ingress.kubernetes.io/healthcheck-path: /check_alive
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
```

Thanks for the starting point, made this much easier to test!  The one thing that won't work is anything that requires SPDY (kubectl exec/cp/port-forward)

**Comment by alenhodzic85** [comment]
Hi. First of all, thanks for setting this up in such short time.
Now please help me set it up. Here is what I have done:

1. Pre-requisites: ALB Ingress is already there with ACM certs, everything is working for another host.
2. Installed dashboard with default values
3. Create ns, add/update helm chart repo
4. Installed operator with default values, seems ok
5. Manually created `orchestra-secrets-source` secret in `openunision `namespace with a field `OIDC_CLIENT_SECRET` from Azure App
6. Installed helm charts with the values below (do I need to insall both?)
`helm install orchestra-login-azuread tremolo/orchestra-login-azuread -n openunison -f values.yaml `- OK

```
helm install orchestra tremolo/orchestra --namespace openunison -f values.yaml
Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1-ingress?timeout=10s": context deadline exceeded
```

```
values.yaml
network:
  openunison_host: "k8sou.domain.example"
  dashboard_host: "k8sdb.domain.example"
  api_server_host: "k8sapi.domain.example"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://SOMENUMBERS.gr7.SOMEREGION.eks.amazonaws.com #Is this needed for EKS?
  force_redirect_to_tls: false
  createIngressCertificate: false
  ingress_type: simple
  service_type:	NodePort
  ingress_annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: "cert_arn"
    alb.ingress.kubernetes.io/healthcheck-path: /check_alive
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"


image: docker.io/tremolosecurity/openunison-k8s
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: true

impersonation:
  use_jetstack: true
  jetstack_oidc_proxy_image: docker.io/tremolosecurity/kube-oidc-proxy:latest
  explicit_certificate_trust: true

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
  require_session: true
  
certs:
  use_k8s_cm: false

trusted_certs: []
monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

# Uncomment one of the below options for authentication

#active_directory:
#  base: cn=users,dc=ent2k12,dc=domain,dc=com
#  host: "192.168.2.75"
#  port: "636"
#  bind_dn: "cn=Administrator,cn=users,dc=ent2k12,dc=domain,dc=com"
#  con_type: ldaps
#  srv_dns: "false"

oidc:
 client_id: client_id
 issuer: https://login.microsoftonline.com/TenantID/v2.0/
 user_in_idtoken: false
 domain: ""
 scopes: openid email profile
 claims:
   sub: preferred_username
   email: email
   given_name: given_name
   family_name: family_name
   display_name: name
   groups: roles

azure:
  # replace with the value from Directory (tenant) ID from the overview screen of your app registration
  tennant_id: TenantID


#github:
#  client_id: d85d77c55a08c9bcbb15
#  teams: TremoloSecurity/

#saml:
#  idp_url: "https://portal.apps.tremolo.io/idp-test/metadata/dfbe4040-cd32-470e-a9b6-809c8f857c40"


  

network_policies:
  enabled: false
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: false
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []
  
openunison:
  replicas: 1
  non_secret_data:
    K8S_DB_SSO: oidc
    PROMETHEUS_SERVICE_ACCOUNT: system:serviceaccount:monitoring:prometheus-k8s
    SHOW_PORTAL_ORGS: "false"
  secrets: []
  html:
    image: docker.io/tremolosecurity/openunison-k8s-html
  enable_provisioning: false
  include_auth_chain: azuread-load-groups
  #az_groups:
  #- CN=k8s-users,CN=Users,DC=ent2k12,DC=domain,DC=com

#myvd_configmap: myvdconfig

# For Namespace as a Service

#database:
#  hibernate_dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  quartz_dialect: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql://mariadb.mariadb.svc.cluster.local:3306/unison
#  user: unison
#  validation: SELECT 1

#smtp:
#  host: blackhole.blackhole.svc.cluster.local
#  port: 1025
#  user: "none"
#  from: donotreply@domain.com
#  tls: false
```
