### ISSUE TITLE
Secure another service in kubernetes cluster

### ISSUE THREAD

**Issue by mirisu2** [OpenUnison/openunison-k8s#32]
Hello.
Can I secure access for another service then kubernetes dashboard?
For example, I deploy some service. When I access url of new service I want service redirect to openunison and after success authentication I redirect to service.
Something like oauth2-proxy or gogatekeeper.

**Comment by mlbiam** [comment]
Absolutely. https://openunison.github.io/documentation/custom-sso/ gives details on how to add applications to openunison via it's built in reverse proxy or using openid connect. Which apps are you looking to integrate?

**Comment by mirisu2** [comment]
> 

Thanks for the quick response! I have deployed grafana, and I would like to secure grafana ingress

**Comment by mirisu2** [comment]
reverse proxy - I think would be better.

**Comment by mlbiam** [comment]
> reverse proxy - I think would be better.

Great.  So you can use the same host your openunison since grafana runs off it's own `/grafana` path.  the integration will be similar to https://openunison.github.io/documentation/custom-sso/#using-openunisons-host with a couple of additions:

1.  Create a `ResultGroup` that will add the user's id to a header:

```yaml
---
apiVersion: openunison.tremolo.io/v1
kind: ResultGroup
metadata:
  name: user-header
  namespace: openunison
spec:
- resultType: header
  source: user
  value: X-WEBAUTH-USER=uid
```

2.  In your `Application` object, add the `azSuccess` result to `spec.urls[0].results` :

```yaml
---
apiVersion: openunison.tremolo.io/v1
kind: Application
metadata:
  name: grafana
  namespace: openunison
spec:
  azTimeoutMillis: 3000
  isApp: true
  urls:
  - hosts:
    - "#[OU_HOST]"
    filterChain:
    - className: com.tremolosecurity.proxy.filters.XForward
      params:
        createHeaders: "true"
    - className: com.tremolosecurity.proxy.filters.HideCookie
      params: {}
    uri: "/grafana"
    # update URL to point to the Grafana `Service`
    proxyTo: "http://grafana.monitoring.svc:9090${fullURI}"
    authChain: login-service
    azRules:
    - scope: dn
      constraint: o=Tremolo
    results:
      azSuccess: user-header
      azFail: default-login-failure
    overrideHost: true
    overrideReferer: true
  cookieConfig:
    sessionCookieName: tremolosession
    domain: "#[OU_HOST]"
    secure: true
    httpOnly: true
    logoutURI: "/logout"
    keyAlias: session-unison

```

Once you do that you'll need to configure grafana to accept the `X-WEBAUTH-USER` header as the user
