### ISSUE TITLE
Non-critical error occurred during resource retrieval: Unauthorized

### ISSUE THREAD

**Issue by mirisu2** [OpenUnison/openunison-k8s#36]
Hello.

I deployed `openunison-operator`, made `secret`, deployed `orchestra` , `orchestra-login-portal` and dashboard.  `api-server` config also was fixed. I created ClusterRoleBinding.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: CN=k8s_cluster_admin,OU=Special Users And Groups,DC=mydomain,DC=com
```
I access auth page, enter login/possword and voila! I'm authorized. But when I open dashbord I see I'm not authorized.
In the dashboard pod logs I see
```
Non-critical error occurred during resource retrieval: Unauthorized
```
On a k8sou page, in the Role part of page I see my `CN=k8s_cluster_admin,OU=Special Users And Groups,DC=mydomain,DC=com`
If I take token from `Kubernetes Tokens` page and use generated kube-config file I have an error `error: You must be logged in to the server (Unauthorized)`
How is it possible? What should I check?
