### ISSUE TITLE
Can't login into openunison portal

### ISSUE THREAD

**Issue by Mihai-CMM** [OpenUnison/openunison-k8s#4]
Hello
I (think) i have openunison integrated with AD but whenever i try to login to openunsion i get 403

2021/11/05 13:21:20 [error] 7#7: *268 directory index of "/var/www/html/" is forbidden, client: 127.0.0.6, server: , request: "GET / HTTP/1.1", host: "openunison.k8s-its.test.salt.ch:32000"
127.0.0.6 - - [05/Nov/2021:13:21:20 +0000] "GET / HTTP/1.1" 403 564 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "-"
127.0.0.6 - - [05/Nov/2021:13:21:22 +0000] "GET /nginx-health HTTP/1.1" 200 8 "-" "kube-probe/1.22" "-"
127.0.0.6 - - [05/Nov/2021:13:21:22 +0000] "GET /nginx-health HTTP/1.1" 200 8 "-" "kube-probe/1.22" "-"

[mcostach@itsk8s01-cr-test openunison]$ kubectl get all -n openunison
NAME                                                 READY   STATUS    RESTARTS       AGE
pod/openunison-operator-7cd48b58f4-m9f5j             2/2     Running   1 (126m ago)   126m
pod/openunison-orchestra-76cbd994d4-vhwlv            2/2     Running   0              74m
pod/ouhtml-orchestra-login-portal-55ccc56cc6-vwhpr   2/2     Running   0              71m

NAME                                    TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/openunison-orchestra            ClusterIP   10.233.59.12   <none>        443/TCP,80/TCP   74m
service/ouhtml-orchestra-login-portal   NodePort    10.233.44.81   <none>        8080:32000/TCP   71m

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/openunison-operator             1/1     1            1           126m
deployment.apps/openunison-orchestra            1/1     1            1           74m
deployment.apps/ouhtml-orchestra-login-portal   1/1     1            1           71m

NAME                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/openunison-operator-7cd48b58f4             1         1         1       126m
replicaset.apps/openunison-orchestra-76cbd994d4            1         1         1       74m
replicaset.apps/ouhtml-orchestra-login-portal-55ccc56cc6   1         1         1       71m

NAME                                  SCHEDULE    SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/check-certs-orchestra   0 2 * * *   False     0        <none>          74m

I am trying to access openunison portal though a NodePort 
I am getting the same result if i curl locally

[mcostach@itsk8s01-cr-test openunison]$ curl 10.233.44.81:8080
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
Thanks for any help

**Comment by mlbiam** [comment]
Can you share your values.yaml?

**Comment by mlbiam** [comment]
It looks like you're trying to access the `service/ouhtml-orchestra-login-portal` `Service` directly.  I'm assuming you made that `Service` a `NodePort`?  You're getting that message because you're trying to access a static NGINX pod that just hosts the pages for OpenUnison's portal.  That's not OpenUnison (we separate them out to make it easier to customize).

When trying to login, go to https://`network.openunison_host`/ (where `network.openunison_host` is what you used for that value in your values.yaml).  That host should point to your load balancer which in turn forwards to your `Ingress` controller.

**Comment by Mihai-CMM** [comment]
Sorry not sure i quite get it ..
I don't have an LB in front and i am using istio. Is just a validation env right now
Is there a way to test it without that LB?

[mcostach@itsk8s01-cr-test openunison]$ kubectl get virtualservice -n openunison
NAME                   GATEWAYS                           HOSTS                                                                  AGE
openunison-orchestra   ["openunison-gateway-orchestra"]   ["openunison.k8s-its.test.salt.ch","dashboard.k8s-its.test.salt.ch"]   106m
[mcostach@itsk8s01-cr-test openunison]$ kubectl get gateway -n openunison
NAME                           AGE
openunison-gateway-orchestra   106m

**Comment by mlbiam** [comment]
I see.  the main issue is that openunison expects to be running on standard ports [80/443].  If you don't have a load balancer in front of your istio deployment, the easiest thing is to patch your `istio-ingressgateway` to run with a `hostPort` of 8080 and 443:

```
kubectl patch deployments istio-ingressgateway -n istio-system -p '{"spec":{"template":{"spec":{"containers":[{"name":"istio-proxy","ports":[{"containerPort":15021,"protocol":"TCP"},{"containerPort":8080,"hostPort":80,"protocol":"TCP"},{"containerPort":8443,"hostPort":443,"protocol":"TCP"},{"containerPort":31400,"protocol":"TCP"},{"containerPort":15443,"protocol":"TCP"},{"containerPort":15090,"name":"http-envoy-prom","protocol":"TCP"}]}]}}}}'
```

once the `istio-ingressgateway` pod is running, assuming `openunison.k8s-its.test.salt.ch` points to a node in your cluster, you should be able to login to openunison through your Istio deployment

**Comment by Mihai-CMM** [comment]
Thank you for your time 
Still not working it seems it reaches the istio proxy on the  node where openunison pods are running 
`
[2021-11-05T15:14:29.777Z] "GET / HTTP/1.1" 301 - direct_response - "-" 0 0 0 - "172.19.108.119" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "26704365-0ec5-9d8c-ad7a-4a2d899c2e9d" "openunison.k8s-its.test.salt.ch" "-" - - 10.233.82.130:8080 172.19.108.119:58323 - -`

istio-system           istio-ingressgateway-85c6d5d85f-zn4mm                        1/1     Running     0               16m    10.233.82.130   itsk8s02-cr-test   <none>           <none>

```
NAME                                             READY   STATUS    RESTARTS      AGE   IP              NODE               NOMINATED NODE   READINESS GATES
openunison-operator-7cd48b58f4-qv52b             2/2     Running   1 (29m ago)   29m   10.233.82.126   itsk8s02-cr-test   <none>           <none>
openunison-orchestra-76cbd994d4-6v2bm            2/2     Running   0             27m   10.233.82.128   itsk8s02-cr-test   <none>           <none>
ouhtml-orchestra-login-portal-55ccc56cc6-h8hs7   2/2     Running   0             26m   10.233.82.129   itsk8s02-cr-test   <none>           <none>
```

But then nothing happens  I see no hit in login portal logs

`[mcostach@itsk8s01-cr-test ~]$ kubectl logs ouhtml-orchestra-login-portal-55ccc56cc6-h8hs7 -n openunison | grep -v health
[mcostach@itsk8s01-cr-test ~]$
`



Are these all the components for openunison

```
`[mcostach@itsk8s01-cr-test ~]$ kubectl get all -n openunison
NAME                                                 READY   STATUS    RESTARTS      AGE
pod/openunison-operator-7cd48b58f4-qv52b             2/2     Running   1 (33m ago)   34m
pod/openunison-orchestra-76cbd994d4-6v2bm            2/2     Running   0             32m
pod/ouhtml-orchestra-login-portal-55ccc56cc6-h8hs7   2/2     Running   0             31m

NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/openunison-orchestra            ClusterIP   10.233.22.228   <none>        443/TCP,80/TCP   32m
service/ouhtml-orchestra-login-portal   ClusterIP   10.233.35.223   <none>        8080/TCP         31m

NAME                                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/openunison-operator             1/1     1            1           34m
deployment.apps/openunison-orchestra            1/1     1            1           32m
deployment.apps/ouhtml-orchestra-login-portal   1/1     1            1           31m

NAME                                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/openunison-operator-7cd48b58f4             1         1         1       34m
replicaset.apps/openunison-orchestra-76cbd994d4            1         1         1       32m
replicaset.apps/ouhtml-orchestra-login-portal-55ccc56cc6   1         1         1       31m

NAME                                  SCHEDULE    SUSPEND   ACTIVE   LAST SCHEDULE   AGE
cronjob.batch/check-certs-orchestra   0 2 * * *   False     0        <none>          32m
```
`

When i run login chart i get this failure but the pods seems ok
`failed to create resource: Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": Post "https://openunison-orchestra.openunison.svc:443/k8s/webhooks/v1/applications?timeout=5s": x509: certificate signed by unknown authority`

**Comment by Mihai-CMM** [comment]
I will install metalLB and get back with the findings after i have also the LB in front . Thank you again

**Comment by mlbiam** [comment]
> When i run login chart i get this failure but the pods seems ok
failed to create resource: Internal error occurred: failed calling webhook "applications-openunison.tremolo.io": Post "https://openunison-orchestra.openunison.svc:443/k8s/webhooks/v1/applications?timeout=5s": x509: certificate signed by unknown authority

this usually happens with repeated upgrade/installs of the `orchestra` charts but doesn't trigger the operator to update the certs.  The easiest way to fix this is to add an annotation to the `openunison-orchestra` `OpenUnison` object.  that usually resolves that so you can deploy the `orchestra-login-portal` chart.

**Comment by Mihai-CMM** [comment]
You were right about the certificate.
I've destroyed the cluster and redeployed from scratch with no issues deploying login-portal charts 

Now I have metalLb that assigns 10.193.13.200 to istio ingress gateway .
I have the dns pointing openunison.k8s-its.test.salt.ch  to 10.193.13.200

I see connection attempt in istio logs

`[2021-11-05T18:43:44.571Z] "GET / HTTP/1.1" 301 - direct_response - "-" 0 0 0 - "10.233.65.31" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "b8e59d5e-727a-9d19-8945-b2603f1e3faa" "openunison.k8s-its.test.salt.ch" "-" - - 10.233.66.246:8080 10.233.65.31:54390 - -
`
In browser I get  "This site can’t be reached"

I still dont see anything in login-portal  pod
`[mcostach@itsk8s01-cr-test ~]$ kubectl logs ouhtml-orchestra-login-portal-55ccc56cc6-5smtc -n openunison | grep -v health
[mcostach@itsk8s01-cr-test ~]$
`

istio sidecar seems ok

```
`[mcostach@itsk8s01-cr-test ~]$ kubectl logs ouhtml-orchestra-login-portal-55ccc56cc6-5smtc -c istio-proxy -n openunison  | tail -4

2021-11-05T18:40:21.993510Z     info    cache   returned workload trust anchor from cache       ttl=23h59m59.006493746s
2021-11-05T18:40:21.993565Z     info    ads     SDS: PUSH for node:ouhtml-orchestra-login-portal-55ccc56cc6-5smtc.openunison resources:1 size:1.1kB resource:ROOTCA
2021-11-05T18:40:23.437824Z     info    Initialization took 1.600175828s
2021-11-05T18:40:23.437854Z     info    Envoy proxy is ready
`

```



```
`[mcostach@itsk8s01-cr-test ~]$ kubectl get pods -n openunison -o wide
NAME                                             READY   STATUS    RESTARTS      AGE   IP              NODE               NOMINATED NODE   READINESS GATES
openunison-operator-7cd48b58f4-kjnhk             2/2     Running   1 (29m ago)   29m   10.233.65.49    itsk8s02-cr-test   <none>           <none>
openunison-orchestra-76cbd994d4-zfnz8            2/2     Running   0             29m   10.233.65.22    itsk8s02-cr-test   <none>           <none>
ouhtml-orchestra-login-portal-55ccc56cc6-5smtc   2/2     Running   0             26m   10.233.65.168   itsk8s02-cr-test   <none>           <none>

[mcostach@itsk8s01-cr-test ~]$ kubectl get svc -n openunison -o wide
NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE   SELECTOR
openunison-orchestra            ClusterIP   10.233.8.101   <none>        443/TCP,80/TCP   29m   application=openunison-orchestra
ouhtml-orchestra-login-portal   ClusterIP   10.233.8.221   <none>        8080/TCP         27m   app=ouhtml-orchestra-login-portal

[mcostach@itsk8s01-cr-test ~]$ kubectl get endpoints -n openunison -o wide
NAME                            ENDPOINTS                             AGE
openunison-orchestra            10.233.65.22:8080,10.233.65.22:8443   29m
ouhtml-orchestra-login-portal   10.233.65.168:8080                    27m
`

```
I think istio integration is ok

```
`[mcostach@itsk8s01-cr-test ~]$ kubectl get gateway -n openunison
NAME                           AGE
openunison-gateway-orchestra   29m

[mcostach@itsk8s01-cr-test ~]$ kubectl get virtualservice -n openunison
NAME                   GATEWAYS                           HOSTS                                                                  AGE
openunison-orchestra   ["openunison-gateway-orchestra"]   ["openunison.k8s-its.test.salt.ch","dashboard.k8s-its.test.salt.ch"]   30m
` 

```
Any clue what to do next ?

Thank you

**Comment by mlbiam** [comment]
>  still dont see anything in login-portal pod
[mcostach@itsk8s01-cr-test ~]$ kubectl logs ouhtml-orchestra-login-portal-55ccc56cc6-5smtc -n openunison | grep -v health [mcostach@itsk8s01-cr-test ~]$

Wrong `Pod`:

```
kubectl logs -f -l app=openunison-orchestra -n openunison
```

Can you post  your values.yaml?  Also, have you deployed Kiali?  With istio I find if i'm running into issues kiali with portforwarding in anonymous mode really helps.

**Comment by Mihai-CMM** [comment]
I am not having Kiali after redeploy 

On openunison pod i only see this 
`
[2021-11-06 07:24:58,183][XNIO-1 task-4] INFO  AccessLog - [AzSuccess] - k8sidp - https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration - uid=Anonymous,o=Tremolo - NONE [127.0.0.1] - [f9ee877e637f4b22c0781073fae0092599e1e8a7c]
[2021-11-06 07:24:58,233][XNIO-1 task-4] INFO  AccessLog - [AzSuccess] - k8sidp - https://127.0.0.1:8443/auth/idp/k8sIdp/.well-known/openid-configuration - uid=Anonymous,o=Tremolo - NONE [127.0.0.1] - [fb4ed4cac1304734d260fd4e8c48c531397852806]
` 

Here is the values.yaml file content

````
network:
  openunison_host: "openunison.k8s-its.test.salt.ch"
  dashboard_host: "dashboard.k8s-its.test.salt.ch"
  api_server_host: "api.k8s-its.test.salt.ch"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://api.k8s-its.test.salt.ch:6443
  force_redirect_to_tls: false
  ingress_type: istio
  ingress_certificate: "ou-tls-certificate"
  istio.selectors: "istio: ingressgateway"
  createIngressCertificate: true

cert_template:
  ou: "Kubernetes"
  o: "MyOrg"
  l: "My Cluster"
  st: "State of Cluster"
  c: "MyCountry"


image: docker.io/tremolosecurity/betas:ou-k8s-1024
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: kubernetes
enable_impersonation: false

impersonation:
  use_jetstack: false
  jetstack_oidc_proxy_image: quay.io/jetstack/kube-oidc-proxy:v0.3.0
  explicit_certificate_trust: true

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
certs:
  use_k8s_cm: false

trusted_certs:
  - name: ldaps
    pem_b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURORENDQWh5Z0F3SUJBZ0lRYlJOajZSS3F0cVZQdlc2NXFaeFhYakFOQmdrcWhraUc5dzBCQVFVRkFEQWkKTVNBd0hnWURWUVFEREJkQlJFWlRMa1ZPVkRKTE1USXVSRTlOUVVsT0xrTlBUVEFlRncweE5EQXpNamd3TVRBMQpNek5hRncweU5EQXpNalV3TVRBMU16TmFNQ0l4SURBZUJnTlZCQU1NRjBGRVJsTXVSVTVVTWtzeE1pNUVUMDFCClNVNHVRMDlOTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyczlKa2VOQUhPa1EKMVFZSmdqZWZVd2Nhb2dFTWNhVy9rb0ErYnU5eGJyNHJIeS8yZ04va2M4T2tvUHV3Si9uTmxPSU8rcytNYm5YUwpMOW1VVEM0T0s3dHJrRWppS1hCK0QrVlNZeTZpbVhoNnpwQnROYmVaeXgrcmRCbmFPdjNCeVpSbm5FQjhMbWhNCnZIQSs0Zi90OWZ4LzJ2dDZ3UHgvL1ZnSXE5eXVZWVVRUkxtMVdqeVVCRnJaZUdvU3BQbTBLZXdtK0IwYmhtTWIKZHlDKzNmaGFLQytVazFOUG9kRTI5NzNqTEJaSmVsWnhzWlk0MFd3OHpZUXdkR1lJYlhxb1RjKzFhL3g0ZjFFbgptNEFOcWdnSHR3K05xOHpoc3MzeVR0WStVWUtEUkJJTGRMVlpRaEhKRXhlMGtBZWlzZ014SS9iQndPMUhickZWCit6U25rK252Z1FJREFRQUJvMll3WkRBekJnTlZIU1VFTERBcUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SUcKQ2lzR0FRUUJnamNVQWdJR0NDc0dBUVVGQndNRE1CMEdBMVVkRGdRV0JCVHlKVWZZNjZ6WWJtOWkweGVZSHVGSQo0TU43dURBT0JnTlZIUThCQWY4RUJBTUNCU0F3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQU01a3o5T0tOU3VYCjh3NE5PZ25mSUZkYXpkMG5QbElVYnZEVmZRb055OVEwUzFTRlVWTWVrSVBOaVZoZkd6eWE5SXdSdEdiMVZhQlEKQVEyT1JJekhyOEEycjVVTkx4M21GanBKbWVPeFF3bFYwWCtnOHMrMjUzS1ZGeE9wUkU2eXlhZ24vQnh4cHRUTAphMVo0cWVRSkxENDJsZDFxR2xSd0Z0VlJtVkZaelZYVnJwdTdOdUZkM3Zsbm5PL3FLV1hVK3VNc2ZYdHNsMTNuCmVjMWt3MUV3cTJqbks4V0ltS1RRNy85V2JhSVkwZ3g4bW93Q0pTT3NScTBURTd6Sy9ONTVkck4xd1hKVnhXZTUKNE4zMmVDcW90WHk5ajlsemRrTmE3YXdiOXEzOG5XVnhQK3ZhNWpxTklEbGxqQjZ0RXh5NW4zczd0NktLNmc1agpUWmdWcXJaMyttcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoK

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s


active_directory:
  base: OU=Domain-Service-Accounts,OU=Salt-Test,DC=salt-test,DC=ch
  host: "10.192.14.2"
  port: "636"
 # bind_dn: "cn=Administrator,cn=users,dc=ent2k12,dc=domain,dc=com"
  bind_dn: "CN=k8s Service Account,OU=Domain-Service-Accounts,OU=Salt-Test,DC=salt-test,DC=ch"
  con_type: ldap
  srv_dns: "false"





network_policies:
  enabled: false
  ingress:
    enabled: false
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: false
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: false
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []

openunison:
  replicas: 1
  non_secret_data:
    K8S_DB_SSO: oidc
    PROMETHEUS_SERVICE_ACCOUNT: system:serviceaccount:monitoring:prometheus-k8s
    SHOW_PORTAL_ORGS: "false"
  secrets: []
  html:
    image: docker.io/tremolosecurity/openunison-k8s-html
  enable_provisioning: false
  #az_groups:
  #- CN=k8s-users,CN=Users,DC=ent2k12,DC=domain,DC=com
```

`
