### ISSUE TITLE
[Helm] Installation fails if a long (> 9 characters) release name is chosen

### ISSUE THREAD

**Issue by mway-niels** [OpenUnison/openunison-k8s#63]
values.yaml:
```
network:
  openunison_host: "ou.sso.example.com"
  dashboard_host: "sso.example.com"
  api_server_host: "api.sso.example.com"
  createIngressCertificate: false
  ingress_type: traefik
  ingress_annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
```

Error:
```
% helm upgrade --install -n openunison openunison tremolo/orchestra -f openunison/values.yaml
Error: UPGRADE FAILED: cannot patch "openunison-openunison" with kind Ingress: Ingress.extensions "openunison-openunison" is invalid: [spec.rules[0].http.paths[0].backend.service.port.name: Invalid value: "https-openunison": must be no more than 15 characters, spec.rules[1].http.paths[0].backend.service.port.name: Invalid value: "https-openunison": must be no more than 15 characters]
```
