### ISSUE TITLE
Audience URI and SSO URL in okta for SAML2

### ISSUE THREAD

**Issue by eyupdzhanY1** [OpenUnison/openunison-k8s#71]
![image](https://user-images.githubusercontent.com/101409648/226707084-814d30f9-1d65-4bf6-9704-e8ece3066c0a.png)

If set to base https://k8sou.HOST.com/ it keeps redirected to login splash , what is the correct values  ? 

Looping networking tab from chrome.
![image](https://user-images.githubusercontent.com/101409648/226707747-05370194-2196-47b4-bc92-ca1feaf9b5b7.png)

**Comment by eyupdzhanY1** [comment]
If there is an example SAML configuration in okta would help this issue i believe.
![image](https://user-images.githubusercontent.com/101409648/226878377-81da5344-84a9-476f-a3f8-e0ce1b19e836.png)

**Comment by mlbiam** [comment]
You can grab your metadata from https://k8sou.domain.com/auth/forms/saml2_rp_metadata.jsp (assuming you've gotten openunison deployed?). Curious, why use SAML2 with Okta instead of OIDC?

**Comment by eyupdzhanY1** [comment]
Not in our product plan with okta, oidc requires extra fees as i get to learn.

**Comment by mlbiam** [comment]
@eyupdzhanY1 were you able to upload the saml2 metadata?

**Comment by eyupdzhanY1** [comment]
Upload it where exactly ? @mlbiam I can access it through mentioned link.

**Comment by mlbiam** [comment]
ugh.  didn't realize okta wouldn't let you just run let you upload your metadata.  i'll test it out and get you specific instructions.

**Comment by mlbiam** [comment]
this should get you what you need.

![Screenshot 2023-03-24 at 1 55 00 PM](https://user-images.githubusercontent.com/8249283/227603659-c1e63e25-f999-4b39-b47a-88cf915cc912.png)

**Comment by eyupdzhanY1** [comment]
Thank a lot! Will try this on monday and post an update.

**Comment by eyupdzhanY1** [comment]
Login is successful but I am unable to access dashboard, and in the attributes page there is only user name with email exist. 
user1@domain.com, in the user CRD there is my user generated but instead of "**1**" in the user name we have  "**x-49-x**" and instead of **@** there is "**x-64-x**". How can I assign this user role in the ClusterRoleBinding

**Comment by mlbiam** [comment]
> Login is successful but I am unable to access dashboard,

Can you provide some details?  What do you see on the screen?

> only user name with email exist.

Your username is whatever you specified in the **Application username** section of your SAML2 Okta configuraiton.  By default it's your Okta username.  Looking at your `User` object I see `user1@domain.com`.  Is this not what you were expecting?

> he user CRD there is my user generated but instead of "1" in the user name we have "x-49-x" and instead of @ there is "x-64-x"

This is only used internally by OpenUnison.  The `x-49-x` is used to make sure that any username can be translated into a kubernetes name with its DNS restrictions.  It can be ignored.  The important field is `sub`

> I tried these access user names. None gave me access to dashboard.

this should work:

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
  - kind: User
    name: user1@domain.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

That said, you're using AKS, right?  Did you enable impersonation in your values.yaml? (`enable_impersonation: true`)

**Comment by mlbiam** [comment]
> Login is successful but I am unable to access dashboard,

Can you provide some details?  What do you see on the screen?

> only user name with email exist.

Your username is whatever you specified in the **Application username** section of your SAML2 Okta configuraiton.  By default it's your Okta username.  Looking at your `User` object I see `user1@domain.com`.  Is this not what you were expecting?

> he user CRD there is my user generated but instead of "1" in the user name we have "x-49-x" and instead of @ there is "x-64-x"

This is only used internally by OpenUnison.  The `x-49-x` is used to make sure that any username can be translated into a kubernetes name with its DNS restrictions.  It can be ignored.  The important field is `sub`

> I tried these access user names. None gave me access to dashboard.

this should work:

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
  - kind: User
    name: user1@domain.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

That said, you're using AKS, right?  Did you enable impersonation in your values.yaml? (`enable_impersonation: true`)

**Comment by eyupdzhanY1** [comment]
@mlbiam I am using AKS, and impersonation was set to false. Enabled it now.
![image](https://user-images.githubusercontent.com/101409648/227944175-b0179d8e-0d89-41a9-b83c-a76568a17779.png)

**Comment by mlbiam** [comment]
Odd, same thing we saw in https://github.com/OpenUnison/openunison-k8s/issues/70#issuecomment-1478330257. Try following the same steps?

**Comment by mlbiam** [comment]
Right, delete the `ou-tls-certificate` `Secret` and redeploy. That will force the operator to create a new secret with the correct host name for your API proxy

**Comment by eyupdzhanY1** [comment]
@mlbiam The secret does not exist but network.createIngressCertificate is false.

**Comment by mlbiam** [comment]
Oh, then how are you generating the certificate?

**Comment by eyupdzhanY1** [comment]
I am not, it all sits behind nginx, and there is load balancer IP.

**Comment by mlbiam** [comment]
so it's a wildcard certificate?  is your `network.api_server_host` set to a DNS entry that points to that NGINX?  Please post your values.yaml

**Comment by eyupdzhanY1** [comment]
```
network:
  openunison_host: "k8sou.test.domain.com"
  dashboard_host: "k8sdb.test.domain.com"
  api_server_host: "k8sapi.test.domain.com"
  session_inactivity_timeout_seconds: 900
  k8s_url: https://hcp.eastus2.azmk8s.io:443
  force_redirect_to_tls: true
  createIngressCertificate: false
  ingress_type: nginx
  ingress_annotations: {}

cert_template:
  ou: "Kubernetes"
  o: "domain"
  l: "Production Cluster"
  st: "East US 2"
  c: "USA"

image: docker.io/tremolosecurity/openunison-k8s
myvd_config_path: "WEB-INF/myvd.conf"
k8s_cluster_name: openunison-cp
enable_impersonation: true

impersonation:
  use_jetstack: true
  jetstack_oidc_proxy_image: docker.io/tremolosecurity/kube-oidc-proxy:latest
  explicit_certificate_trust: true

dashboard:
  namespace: "kubernetes-dashboard"
  cert_name: "kubernetes-dashboard-certs"
  label: "k8s-app=kubernetes-dashboard"
  service_name: kubernetes-dashboard
  require_session: true

certs:
  use_k8s_cm: false

trusted_certs:
  - name: okta-cert
    pem_b64: Certificate in base64

monitoring:
  prometheus_service_account: system:serviceaccount:monitoring:prometheus-k8s

saml:
  idp_url: "https://domain.okta.com/app/STRING/sso/saml/metadata"

network_policies:
  enabled: false
  ingress:
    enabled: true
    labels:
      app.kubernetes.io/name: ingress-nginx
  monitoring:
    enabled: true
    labels:
      app.kubernetes.io/name: monitoring
  apiserver:
    enabled: false
    labels:
      app.kubernetes.io/name: kube-system

services:
  enable_tokenrequest: false
  token_request_audience: api
  token_request_expiration_seconds: 600
  node_selectors: []

openunison:
  replicas: 1
  non_secret_data:
    K8S_DB_SSO: saml2
    PROMETHEUS_SERVICE_ACCOUNT: system:serviceaccount:monitoring:prometheus-k8s
    SHOW_PORTAL_ORGS: "false"
  secrets: []
  html:
    image: docker.io/tremolosecurity/openunison-k8s-html
  enable_provisioning: false
  use_standard_jit_workflow: true
```

**Comment by mlbiam** [comment]
Is the ingress signed by a commercial CA?  or is it an internal CA?  Is this CA distributed to your workstation where you're running kubectl from?

**Comment by eyupdzhanY1** [comment]
It is signed by commercial CA, it works fine as long as you are within the company network, had no issues with TLS so far.

**Comment by eyupdzhanY1** [comment]
Adding wildcard certificate as ou-tls-certificate secret first, then deploying worked for connection.
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sou-admins
subjects:
  - kind: User
    name: "user@domain.com"
 roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
 ```
 
 Worked for me , user is whatever "sub" is under openunison.tremolo.io CRD's user resource.
